# Analysis of corrupted data files
## File 1: Group_4_weather_in_denver

In [2]:
# loading pandas for creating a dataframe
import pandas as pd 

# loading the data
df= pd.read_csv('Group_4_Weather_in_Denver_corrupted.txt', sep=',')

## Taking a look at the datas structure

In [3]:
#displaying the first few rows
df.head(5)

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,TEMP,TEMP_ATTRIBUTES,DEWP,DEWP_ATTRIBUTES,...,MXSPD,GUST,MAX,MAX_ATTRIBUTES,MIN,MIN_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SNDP,FRSHTT
0,72565003017,2018-01-01,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",284.75,24,5.5,24,...,9.9,999.9,28.0,,3.0,,0.0,G,999.9,1000
1,72565003017,2018-01-02,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",294.35,24,7.3,24,...,9.9,999.9,43.0,,3.0,,0.0,G,999.9,0
2,72565003017,2018-01-03,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",294.35,24,3.0,24,...,15.9,24.1,53.1,,10.9,,0.0,G,999.9,0
3,72565003017,2018-01-04,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",307.75,24,11.6,24,...,8.9,999.9,53.1,,17.1,,0.0,G,999.9,0
4,72565003017,2018-01-05,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",309.45,24,11.4,24,...,14.0,999.9,55.9,,23.0,,0.0,G,999.9,0

In [4]:
#getting some basic info
df.info()
#finding out how man rows the dataset contains
total_rows = len(df)

print(total_rows)
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   STATION           366 non-null    object
 1   DATE              366 non-null    object
 2   LATITUDE          366 non-null    float64
 3   LONGITUDE         366 non-null    float64
 4   ELEVATION         366 non-null    float64
 5   NAME              366 non-null    object
 6   TEMP              366 non-null    object
 7   TEMP_ATTRIBUTES   366 non-null    int64
 8   DEWP              366 non-null    float64
 9   DEWP_ATTRIBUTES   366 non-null    int64
 10  SLP               366 non-null    float64
 11  SLP_ATTRIBUTES    366 non-null    int64
 12  STP               366 non-null    float64
 13  STP_ATTRIBUTES    366 non-null    object
 14  VISIB             366 non-null    float64
 15  VISIB_ATTRIBUTES  366 non-null    int64
 16  WDSP              366 non-null    float64
 17  WDSP_ATTRIBUTES   366 non-null    int64
 18  MXSPD             366 non-null    float64
 19  GUST              366 non-null    float64
 20  MAX               366 non-null    float64
 21  MAX_ATTRIBUTES    366 non-null    object
 22  MIN               366 non-null    float64
 23  MIN_ATTRIBUTES    366 non-null    object
 24  PRCP              366 non-null    float64
 25  PRCP_ATTRIBUTES   366 non-null    object
 26  SNDP              366 non-null    float64
 27  FRSHTT            366 non-null    int64
dtypes: float64(14), int64(6), object(8)
memory usage: 80.2+ KB
366
STATION             0
DATE                0
LATITUDE            0
LONGITUDE           0
ELEVATION           0
NAME                0
TEMP                0
TEMP_ATTRIBUTES     0
DEWP                0
DEWP_ATTRIBUTES     0
SLP                 0
SLP_ATTRIBUTES      0
STP                 0
STP_ATTRIBUTES      0
VISIB               0
VISIB_ATTRIBUTES    0
WDSP                0
WDSP_ATTRIBUTES     0
MXSPD               0
GUST                0
MAX                 0
MAX_ATTRIBUTES      0
MIN                 0
MIN_ATTRIBUTES      0
PRCP                0
PRCP_ATTRIBUTES     0
SNDP                0
FRSHTT              0
dtype: int64

### First error: Column date seems to be an object. We should change it to datetime_object for more convenience in mathematic operations

In [5]:

#converting the object to a datetime object, using coerce to be sure that every value is converted or given as NaT (not a time)
df['DATE'] = pd.to_datetime(df['DATE'], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   STATION           366 non-null    object
 1   DATE              366 non-null    datetime64[ns]
 2   LATITUDE          366 non-null    float64
 3   LONGITUDE         366 non-null    float64
 4   ELEVATION         366 non-null    float64
 5   NAME              366 non-null    object
 6   TEMP              366 non-null    object
 7   TEMP_ATTRIBUTES   366 non-null    int64
 8   DEWP              366 non-null    float64
 9   DEWP_ATTRIBUTES   366 non-null    int64
 10  SLP               366 non-null    float64
 11  SLP_ATTRIBUTES    366 non-null    int64
 12  STP               366 non-null    float64
 13  STP_ATTRIBUTES    366 non-null    object
 14  VISIB             366 non-null    float64
 15  VISIB_ATTRIBUTES  366 non-null    int64
 16  WDSP              366 non-null    float64
 17  WDSP_ATTRIBUTES   366 non-null    int64
 18  MXSPD             366 non-null    float64
 19  GUST              366 non-null    float64
 20  MAX               366 non-null    float64
 21  MAX_ATTRIBUTES    366 non-null    object
 22  MIN               366 non-null    float64
 23  MIN_ATTRIBUTES    366 non-null    object
 24  PRCP              366 non-null    float64
 25  PRCP_ATTRIBUTES   366 non-null    object
 26  SNDP              366 non-null    float64
 27  FRSHTT            366 non-null    int64
dtypes: datetime64[ns](1), float64(14), int64(6), object(7)
memory usage: 80.2+ KB

### As we can see there are 366 rows in total. There are 366 non-null values in each column. Therefore no n/a values are found.

In [6]:
df.describe()

,DATE,LATITUDE,LONGITUDE,ELEVATION,TEMP_ATTRIBUTES,DEWP,DEWP_ATTRIBUTES,SLP,SLP_ATTRIBUTES,STP,...,VISIB_ATTRIBUTES,WDSP,WDSP_ATTRIBUTES,MXSPD,GUST,MAX,MIN,PRCP,SNDP,FRSHTT
count,366,366.000000,366.000000,366.000000,366.000000,366.000000,366.0,366.000000,366.000000,366.000000,...,366.0,366.000000,366.0,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,2018-07-12 11:28:31.475409920,39.857874,-104.364589,2096.565574,24.049180,29.465847,24.0,1013.763934,22.609290,833.096175,...,24.0,8.903279,24.0,18.470492,321.093989,97.272404,36.457377,0.024016,950.807923,12351.584699
min,2018-01-01 00:00:00,39.832800,-104.657500,1650.200000,24.000000,-4.100000,24.0,996.900000,10.000000,819.300000,...,24.0,4.100000,24.0,7.000000,14.000000,19.000000,-7.100000,0.000000,1.200000,0.000000
25%,2018-04-02 06:00:00,39.832800,-104.657500,1650.200000,24.000000,18.025000,24.0,1008.925000,23.000000,829.900000,...,24.0,7.200000,24.0,14.000000,26.000000,55.900000,23.000000,0.000000,999.900000,0.000000
50%,2018-07-02 12:00:00,39.832800,-104.657500,1650.200000,24.000000,28.500000,24.0,1013.500000,24.000000,833.450000,...,24.0,8.450000,24.0,18.100000,33.000000,69.100000,34.000000,0.000000,999.900000,0.000000
75%,2018-10-01 18:00:00,39.832800,-104.657500,1650.200000,24.000000,42.275000,24.0,1018.575000,24.000000,836.500000,...,24.0,10.200000,24.0,22.900000,999.900000,88.000000,52.825000,0.000000,999.900000,10000.000000
max,2028-10-30 00:00:00,49.009724,2.547778,165020.000000,42.000000,61.500000,24.0,1038.300000,24.000000,845.400000,...,24.0,23.200000,24.0,40.000000,999.900000,9999.900000,68.000000,0.660000,999.900000,111110.000000
std,NaN,0.479686,5.603710,8539.476244,0.940875,14.717201,0.0,7.115144,2.706222,5.026907,...,0.0,2.557737,0.0,5.958731,445.623409,519.371598,17.204341,0.078841,216.151889,30537.537551

### Trying to find duplicates

In [7]:
#show duplicated rows
print(df[df.duplicated()])
# construct a string that shows the number of duplicates
print(f"number of duplicates: {df.duplicated().sum()}")

         STATION       DATE  LATITUDE  LONGITUDE  ELEVATION  \
365  72565003017 2018-12-31   39.8328  -104.6575     1650.2

                                    NAME    TEMP  TEMP_ATTRIBUTES  DEWP  \
365  DENVER INTERNATIONAL AIRPORT, CO US    23.4               24  11.1

     DEWP_ATTRIBUTES  ...  MXSPD  GUST   MAX MAX_ATTRIBUTES  MIN  \
365               24  ...   21.0  29.9  53.1                 7.0

     MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
365                   0.0                G  999.9    1000

[1 rows x 28 columns]
number of duplicates: 1

### Second error: there is a duplicated row. We can drop it very easily.

In [8]:
#drop the duplicated row
df = df.drop_duplicates()
# check if it was dropped (length should be one less)
print(len(df))

365

### Lets take a look at the data and see if there are any outliers inside the int and float columns

In [9]:
# identify values that could be outliers by using 1.5 x IQR 
for column in df.select_dtypes(include=['float', 'int']).columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    Outliers = df[(df[column] < (Q1 - 1.5 * IQR)) | (df[column] > (Q3 + 1.5 * IQR))]
    print(f"Outliers in column {column}:\n", Outliers)

Outliers in column LATITUDE:
          STATION       DATE   LATITUDE  LONGITUDE  ELEVATION  \
235  72565003017 2018-08-24  49.009724   2.547778     1650.2

                                    NAME    TEMP  TEMP_ATTRIBUTES  DEWP  \
235  DENVER INTERNATIONAL AIRPORT, CO US    76.2               24  38.0

     DEWP_ATTRIBUTES  ...  MXSPD  GUST   MAX MAX_ATTRIBUTES   MIN  \
235               24  ...   17.1  21.0  90.0                 57.9

     MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
235                   0.0                G  999.9       0

[1 rows x 28 columns]
Outliers in column LONGITUDE:
          STATION       DATE   LATITUDE  LONGITUDE  ELEVATION  \
235  72565003017 2018-08-24  49.009724   2.547778     1650.2

                                    NAME    TEMP  TEMP_ATTRIBUTES  DEWP  \
235  DENVER INTERNATIONAL AIRPORT, CO US    76.2               24  38.0

     DEWP_ATTRIBUTES  ...  MXSPD  GUST   MAX MAX_ATTRIBUTES   MIN  \
235               24  ...   17.1  21.0  90.0                 57.9

     MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
235                   0.0                G  999.9       0

[1 rows x 28 columns]
Outliers in column ELEVATION:
         STATION       DATE  LATITUDE  LONGITUDE  ELEVATION  \
70  72565003017 2018-03-12   39.8328  -104.6575   165020.0

                                   NAME    TEMP  TEMP_ATTRIBUTES  DEWP  \
70  DENVER INTERNATIONAL AIRPORT, CO US    35.8               24   7.8

    DEWP_ATTRIBUTES  ...  MXSPD  GUST   MAX MAX_ATTRIBUTES   MIN  \
70               24  ...   15.9  21.0  57.0                 16.0

    MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
70                   0.0                G  999.9       0

[1 rows x 28 columns]
Outliers in column TEMP_ATTRIBUTES:
          STATION       DATE  LATITUDE  LONGITUDE  ELEVATION  \
187  72565003017 2018-07-07   39.8328  -104.6575     1650.2

                                    NAME    TEMP  TEMP_ATTRIBUTES  DEWP  \
187  DENVER INTERNATIONAL AIRPORT, CO US    80.7               42  50.1

     DEWP_ATTRIBUTES  ...  MXSPD  GUST   MAX MAX_ATTRIBUTES   MIN  \
187               24  ...   15.9  27.0  98.1                 60.1

     MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
187                   0.0                G  999.9       0

[1 rows x 28 columns]
Outliers in column DEWP:
 Empty DataFrame
Columns: [STATION, DATE, LATITUDE, LONGITUDE, ELEVATION, NAME, TEMP, TEMP_ATTRIBUTES, DEWP, DEWP_ATTRIBUTES, SLP, SLP_ATTRIBUTES, STP, STP_ATTRIBUTES, VISIB, VISIB_ATTRIBUTES, WDSP, WDSP_ATTRIBUTES, MXSPD, GUST, MAX, MAX_ATTRIBUTES, MIN, MIN_ATTRIBUTES, PRCP, PRCP_ATTRIBUTES, SNDP, FRSHTT]
Index: []

[0 rows x 28 columns]
Outliers in column DEWP_ATTRIBUTES:
 Empty DataFrame
Columns: [STATION, DATE, LATITUDE, LONGITUDE, ELEVATION, NAME, TEMP, TEMP_ATTRIBUTES, DEWP, DEWP_ATTRIBUTES, SLP, SLP_ATTRIBUTES, STP, STP_ATTRIBUTES, VISIB, VISIB_ATTRIBUTES, WDSP, WDSP_ATTRIBUTES, MXSPD, GUST, MAX, MAX_ATTRIBUTES, MIN, MIN_ATTRIBUTES, PRCP, PRCP_ATTRIBUTES, SNDP, FRSHTT]
Index: []

[0 rows x 28 columns]
Outliers in column SLP:
          STATION       DATE  LATITUDE  LONGITUDE  ELEVATION  \
15   72565003017 2018-01-16   39.8328  -104.6575     1650.2
315  72565003017 2018-11-12   39.8328  -104.6575     1650.2
316  72565003017 2018-11-13   39.8328  -104.6575     1650.2

                                    NAME      TEMP  TEMP_ATTRIBUTES  DEWP  \
15   DENVER INTERNATIONAL AIRPORT, CO US    283,45               24  -4.1
315  DENVER INTERNATIONAL AIRPORT, CO US      21.9               24  16.8
316  DENVER INTERNATIONAL AIRPORT, CO US      27.7               24  13.0

     DEWP_ATTRIBUTES  ...  MXSPD   GUST   MAX MAX_ATTRIBUTES   MIN  \
15                24  ...    9.9  999.9  34.0                 -4.0
315               24  ...   13.0  999.9  34.0                 18.0
316               24  ...   11.1  999.9  48.0                 10.0

     MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
15                   0.03                G  999.9       0
315                  0.19                G  999.9    1000
316                  0.01                G    1.2       0

[3 rows x 28 columns]
Outliers in column SLP_ATTRIBUTES:
          STATION       DATE  LATITUDE  LONGITUDE  ELEVATION  \
14   72565003017 2018-01-15   39.8328  -104.6575     1650.2
20   72565003017 2018-01-21   39.8328  -104.6575     1650.2
31   72565003017 2018-02-01   39.8328  -104.6575     1650.2
32   72565003017 2018-02-02   39.8328  -104.6575     1650.2
34   72565003017 2018-02-04   39.8328  -104.6575     1650.2
..           ...        ...       ...        ...        ...
328  72565003017 2018-11-25   39.8328  -104.6575     1650.2
333  72565003017 2018-11-30   39.8328  -104.6575     1650.2
334  72565003017 2018-12-01   39.8328  -104.6575     1650.2
359  72565003017 2018-12-26   39.8328  -104.6575     1650.2
364  72565003017 2018-12-31   39.8328  -104.6575     1650.2

                                    NAME      TEMP  TEMP_ATTRIBUTES  DEWP  \
14   DENVER INTERNATIONAL AIRPORT, CO US    297,95               24  16.0
20   DENVER INTERNATIONAL AIRPORT, CO US      26,9               24  23.4
31   DENVER INTERNATIONAL AIRPORT, CO US      27.5               24  20.5
32   DENVER INTERNATIONAL AIRPORT, CO US      31.3               24  22.2
34   DENVER INTERNATIONAL AIRPORT, CO US      29.3               24  18.5
..                                   ...       ...              ...   ...
328  DENVER INTERNATIONAL AIRPORT, CO US      31.3               24  18.3
333  DENVER INTERNATIONAL AIRPORT, CO US      31.7               24  28.1
334  DENVER INTERNATIONAL AIRPORT, CO US      32.9               24  25.7
359  DENVER INTERNATIONAL AIRPORT, CO US      27.4               24  18.9
364  DENVER INTERNATIONAL AIRPORT, CO US      23.4               24  11.1

     DEWP_ATTRIBUTES  ...  MXSPD   GUST   MAX MAX_ATTRIBUTES   MIN  \
14                24  ...   25.1  999.9  43.0              *  15.1
20                24  ...   24.1   32.1  48.0                 23.0
31                24  ...   12.0  999.9  36.0              *  24.1
32                24  ...   14.0  999.9  60.1                 18.0
34                24  ...   22.0   28.9  57.9                 10.0
..               ...  ...    ...    ...   ...            ...   ...
328               24  ...   40.0   54.0  41.0              *  21.0
333               24  ...   13.0   17.1  48.9                 26.1
334               24  ...   22.9   28.9  44.1                 19.9
359               24  ...   11.1  999.9  46.9                 19.0
364               24  ...   21.0   29.9  53.1                  7.0

     MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
14                *  0.00                G  999.9   11000
20                   0.07                G  999.9  111000
31                *  0.01                G  999.9    1000
32                   0.01                G  999.9  101000
34                   0.00                G  999.9  111000
..              ...   ...              ...    ...     ...
328               *  0.03                G  999.9  101000
333                  0.00                G  999.9  101000
334                  0.05                G  999.9  101000
359                  0.00                G  999.9       0
364                  0.00                G  999.9    1000

[74 rows x 28 columns]
Outliers in column STP:
          STATION       DATE  LATITUDE  LONGITUDE  ELEVATION  \
9    72565003017 2018-01-10   39.8328  -104.6575     1650.2
334  72565003017 2018-12-01   39.8328  -104.6575     1650.2

                                    NAME      TEMP  TEMP_ATTRIBUTES  DEWP  \
9    DENVER INTERNATIONAL AIRPORT, CO US    322.45               24  24.4
334  DENVER INTERNATIONAL AIRPORT, CO US      32.9               24  25.7

     DEWP_ATTRIBUTES  ...  MXSPD  GUST   MAX MAX_ATTRIBUTES   MIN  \
9                 24  ...   17.1  27.0  68.0                 34.0
334               24  ...   22.9  28.9  44.1                 19.9

     MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
9                    0.00                G  999.9   10000
334                  0.05                G  999.9  101000

[2 rows x 28 columns]
Outliers in column VISIB:
          STATION       DATE  LATITUDE  LONGITUDE  ELEVATION  \
0    72565003017 2018-01-01   39.8328  -104.6575     1650.2
1    72565003017 2018-01-02   39.8328  -104.6575     1650.2
14   72565003017 2018-01-15   39.8328  -104.6575     1650.2
20   72565003017 2018-01-21   39.8328  -104.6575     1650.2
21   72565003017 2018-01-22   39.8328  -104.6575     1650.2
..           ...        ...       ...        ...        ...
328  72565003017 2018-11-25   39.8328  -104.6575     1650.2
333  72565003017 2018-11-30   39.8328  -104.6575     1650.2
334  72565003017 2018-12-01   39.8328  -104.6575     1650.2
359  72565003017 2018-12-26   39.8328  -104.6575     1650.2
364  72565003017 2018-12-31   39.8328  -104.6575     1650.2

                                    NAME      TEMP  TEMP_ATTRIBUTES  DEWP  \
0    DENVER INTERNATIONAL AIRPORT, CO US    284.75               24   5.5
1    DENVER INTERNATIONAL AIRPORT, CO US    294.35               24   7.3
14   DENVER INTERNATIONAL AIRPORT, CO US    297,95               24  16.0
20   DENVER INTERNATIONAL AIRPORT, CO US      26,9               24  23.4
21   DENVER INTERNATIONAL AIRPORT, CO US      26,1               24  11.1
..                                   ...       ...              ...   ...
328  DENVER INTERNATIONAL AIRPORT, CO US      31.3               24  18.3
333  DENVER INTERNATIONAL AIRPORT, CO US      31.7               24  28.1
334  DENVER INTERNATIONAL AIRPORT, CO US      32.9               24  25.7
359  DENVER INTERNATIONAL AIRPORT, CO US      27.4               24  18.9
364  DENVER INTERNATIONAL AIRPORT, CO US      23.4               24  11.1

     DEWP_ATTRIBUTES  ...  MXSPD   GUST   MAX MAX_ATTRIBUTES   MIN  \
0                 24  ...    9.9  999.9  28.0                  3.0
1                 24  ...    9.9  999.9  43.0                  3.0
14                24  ...   25.1  999.9  43.0              *  15.1
20                24  ...   24.1   32.1  48.0                 23.0
21                24  ...   27.0   32.1  44.1                  9.0
..               ...  ...    ...    ...   ...            ...   ...
328               24  ...   40.0   54.0  41.0              *  21.0
333               24  ...   13.0   17.1  48.9                 26.1
334               24  ...   22.9   28.9  44.1                 19.9
359               24  ...   11.1  999.9  46.9                 19.0
364               24  ...   21.0   29.9  53.1                  7.0

     MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
0                    0.00                G  999.9    1000
1                    0.00                G  999.9       0
14                *  0.00                G  999.9   11000
20                   0.07                G  999.9  111000
21                   0.23                G    1.2    1000
..              ...   ...              ...    ...     ...
328               *  0.03                G  999.9  101000
333                  0.00                G  999.9  101000
334                  0.05                G  999.9  101000
359                  0.00                G  999.9       0
364                  0.00                G  999.9    1000

[68 rows x 28 columns]
Outliers in column VISIB_ATTRIBUTES:
 Empty DataFrame
Columns: [STATION, DATE, LATITUDE, LONGITUDE, ELEVATION, NAME, TEMP, TEMP_ATTRIBUTES, DEWP, DEWP_ATTRIBUTES, SLP, SLP_ATTRIBUTES, STP, STP_ATTRIBUTES, VISIB, VISIB_ATTRIBUTES, WDSP, WDSP_ATTRIBUTES, MXSPD, GUST, MAX, MAX_ATTRIBUTES, MIN, MIN_ATTRIBUTES, PRCP, PRCP_ATTRIBUTES, SNDP, FRSHTT]
Index: []

[0 rows x 28 columns]
Outliers in column WDSP:
          STATION       DATE  LATITUDE  LONGITUDE  ELEVATION  \
62   72565003017 2018-03-04   39.8328  -104.6575     1650.2
63   72565003017 2018-03-05   39.8328  -104.6575     1650.2
102  72565003017 2018-04-13   39.8328  -104.6575     1650.2
103  72565003017 2018-04-14   39.8328  -104.6575     1650.2
106  72565003017 2018-04-17   39.8328  -104.6575     1650.2
109  72565003017 2018-04-20   39.8328  -104.6575     1650.2
290  72565003017 2018-10-18   39.8328  -104.6575     1650.2
306  72565003017 2018-11-03   39.8328  -104.6575     1650.2

                                    NAME    TEMP  TEMP_ATTRIBUTES  DEWP  \
62   DENVER INTERNATIONAL AIRPORT, CO US    55.1               24   5.4
63   DENVER INTERNATIONAL AIRPORT, CO US    35.2               24   3.2
102  DENVER INTERNATIONAL AIRPORT, CO US    44.2               24  24.2
103  DENVER INTERNATIONAL AIRPORT, CO US    38.5               24  18.7
106  DENVER INTERNATIONAL AIRPORT, CO US    61.9               24  18.9
109  DENVER INTERNATIONAL AIRPORT, CO US    50.9               24  23.7
290  DENVER INTERNATIONAL AIRPORT, CO US    52.0               24  32.0
306  DENVER INTERNATIONAL AIRPORT, CO US    48.0               24  30.0

     DEWP_ATTRIBUTES  ...  MXSPD  GUST   MAX MAX_ATTRIBUTES   MIN  \
62                24  ...   28.0  38.1  71.1                 35.1
63                24  ...   32.1  52.1  53.1              *  26.1
102               24  ...   39.0  49.0  72.0              *  33.1
103               24  ...   29.9  42.0  55.9                 28.9
106               24  ...   38.1  58.1  72.0              *  50.0
109               24  ...   28.0  39.0  69.1                 27.0
290               24  ...   22.9  33.0  69.1                 36.0
306               24  ...   28.0  42.9  64.9                 28.9

     MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
62                   0.00                G  999.9       0
63                *  0.00                G  999.9       0
102               *  0.10                G  999.9   11010
103                  0.05                G  999.9       0
106               *  0.00                G  999.9       0
109                  0.00                G  999.9   10000
290                  0.00                G  999.9       0
306                  0.01                G  999.9   10000

[8 rows x 28 columns]
Outliers in column WDSP_ATTRIBUTES:
 Empty DataFrame
Columns: [STATION, DATE, LATITUDE, LONGITUDE, ELEVATION, NAME, TEMP, TEMP_ATTRIBUTES, DEWP, DEWP_ATTRIBUTES, SLP, SLP_ATTRIBUTES, STP, STP_ATTRIBUTES, VISIB, VISIB_ATTRIBUTES, WDSP, WDSP_ATTRIBUTES, MXSPD, GUST, MAX, MAX_ATTRIBUTES, MIN, MIN_ATTRIBUTES, PRCP, PRCP_ATTRIBUTES, SNDP, FRSHTT]
Index: []

[0 rows x 28 columns]
Outliers in column MXSPD:
          STATION       DATE  LATITUDE  LONGITUDE  ELEVATION  \
102  72565003017 2018-04-13   39.8328  -104.6575     1650.2
106  72565003017 2018-04-17   39.8328  -104.6575     1650.2
328  72565003017 2018-11-25   39.8328  -104.6575     1650.2

                                    NAME    TEMP  TEMP_ATTRIBUTES  DEWP  \
102  DENVER INTERNATIONAL AIRPORT, CO US    44.2               24  24.2
106  DENVER INTERNATIONAL AIRPORT, CO US    61.9               24  18.9
328  DENVER INTERNATIONAL AIRPORT, CO US    31.3               24  18.3

     DEWP_ATTRIBUTES  ...  MXSPD  GUST   MAX MAX_ATTRIBUTES   MIN  \
102               24  ...   39.0  49.0  72.0              *  33.1
106               24  ...   38.1  58.1  72.0              *  50.0
328               24  ...   40.0  54.0  41.0              *  21.0

     MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
102               *  0.10                G  999.9   11010
106               *  0.00                G  999.9       0
328               *  0.03                G  999.9  101000

[3 rows x 28 columns]
Outliers in column GUST:
 Empty DataFrame
Columns: [STATION, DATE, LATITUDE, LONGITUDE, ELEVATION, NAME, TEMP, TEMP_ATTRIBUTES, DEWP, DEWP_ATTRIBUTES, SLP, SLP_ATTRIBUTES, STP, STP_ATTRIBUTES, VISIB, VISIB_ATTRIBUTES, WDSP, WDSP_ATTRIBUTES, MXSPD, GUST, MAX, MAX_ATTRIBUTES, MIN, MIN_ATTRIBUTES, PRCP, PRCP_ATTRIBUTES, SNDP, FRSHTT]
Index: []

[0 rows x 28 columns]
Outliers in column MAX:
         STATION       DATE  LATITUDE  LONGITUDE  ELEVATION  \
49  72565003017 2018-02-19   39.8328  -104.6575     1650.2

                                   NAME    TEMP  TEMP_ATTRIBUTES  DEWP  \
49  DENVER INTERNATIONAL AIRPORT, CO US    20.6               24  12.4

    DEWP_ATTRIBUTES  ...  MXSPD  GUST     MAX MAX_ATTRIBUTES   MIN  \
49               24  ...   22.0  28.0  9999.9                 10.0

    MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
49               *   0.0                G  999.9  101000

[1 rows x 28 columns]
Outliers in column MIN:
 Empty DataFrame
Columns: [STATION, DATE, LATITUDE, LONGITUDE, ELEVATION, NAME, TEMP, TEMP_ATTRIBUTES, DEWP, DEWP_ATTRIBUTES, SLP, SLP_ATTRIBUTES, STP, STP_ATTRIBUTES, VISIB, VISIB_ATTRIBUTES, WDSP, WDSP_ATTRIBUTES, MXSPD, GUST, MAX, MAX_ATTRIBUTES, MIN, MIN_ATTRIBUTES, PRCP, PRCP_ATTRIBUTES, SNDP, FRSHTT]
Index: []

[0 rows x 28 columns]
Outliers in column PRCP:
          STATION       DATE  LATITUDE  LONGITUDE  ELEVATION  \
6    72565003017 2018-01-07   39.8328  -104.6575     1650.2
10   72565003017 2018-01-11   39.8328  -104.6575     1650.2
12   72565003017 2018-01-13   39.8328  -104.6575     1650.2
15   72565003017 2018-01-16   39.8328  -104.6575     1650.2
20   72565003017 2018-01-21   39.8328  -104.6575     1650.2
..           ...        ...       ...        ...        ...
315  72565003017 2018-11-12   39.8328  -104.6575     1650.2
316  72565003017 2018-11-13   39.8328  -104.6575     1650.2
321  72565003017 2018-11-18   39.8328  -104.6575     1650.2
328  72565003017 2018-11-25   39.8328  -104.6575     1650.2
334  72565003017 2018-12-01   39.8328  -104.6575     1650.2

                                    NAME      TEMP  TEMP_ATTRIBUTES  DEWP  \
6    DENVER INTERNATIONAL AIRPORT, CO US    312.95               24  25.2
10   DENVER INTERNATIONAL AIRPORT, CO US    304.15               24  18.9
12   DENVER INTERNATIONAL AIRPORT, CO US    304.35               24  22.7
15   DENVER INTERNATIONAL AIRPORT, CO US    283,45               24  -4.1
20   DENVER INTERNATIONAL AIRPORT, CO US      26,9               24  23.4
..                                   ...       ...              ...   ...
315  DENVER INTERNATIONAL AIRPORT, CO US      21.9               24  16.8
316  DENVER INTERNATIONAL AIRPORT, CO US      27.7               24  13.0
321  DENVER INTERNATIONAL AIRPORT, CO US      28.3               24  20.4
328  DENVER INTERNATIONAL AIRPORT, CO US      31.3               24  18.3
334  DENVER INTERNATIONAL AIRPORT, CO US      32.9               24  25.7

     DEWP_ATTRIBUTES  ...  MXSPD   GUST   MAX MAX_ATTRIBUTES   MIN  \
6                 24  ...   11.1  999.9  62.1                 26.1
10                24  ...   22.9   32.1  57.0                 21.0
12                24  ...   14.0  999.9  48.0                 19.0
15                24  ...    9.9  999.9  34.0                 -4.0
20                24  ...   24.1   32.1  48.0                 23.0
..               ...  ...    ...    ...   ...            ...   ...
315               24  ...   13.0  999.9  34.0                 18.0
316               24  ...   11.1  999.9  48.0                 10.0
321               24  ...   11.1  999.9  48.0              *  19.9
328               24  ...   40.0   54.0  41.0              *  21.0
334               24  ...   22.9   28.9  44.1                 19.9

     MIN_ATTRIBUTES  PRCP  PRCP_ATTRIBUTES   SNDP  FRSHTT
6                    0.01                G  999.9   11000
10                   0.17                G  999.9   11000
12                   0.03                G  999.9    1000
15                   0.03                G  999.9       0
20                   0.07                G  999.9  111000
..              ...   ...              ...    ...     ...
315                  0.19                G  999.9    1000
316                  0.01                G    1.2       0
321               *  0.04                G  999.9    1000
328               *  0.03                G  999.9  101000
334                  0.05                G  999.9  101000


### Since we have no idea what the data means, because we dont have knowledge in this subject, this approach is not helpful this time.

### Lets see if they used different class names for categorization in columns

In [10]:
# show unique values for object columns
for column in df.select_dtypes(include=['object']).columns:
    print(f"Unique values per '{column}':\n", df[column].unique())

Unique values per 'STATION':
 ['72565003017' '72565003O17']
Unique values per 'NAME':
 ['DENVER INTERNATIONAL AIRPORT, CO US'
 'PARIS CHARLES DE GAULLE AIRPORT, FRANCE']
Unique values per 'TEMP':
 ['  284.75' '  294.35' '  307.75' '  309.45' '  313.35' '  312.95'
 '  306.35' '  321.35' '  322.45' '  304.15' '  308.45' '  304.35'
 '  309.05' '  297,95' '  283,45' '  300,25' '  314,15' '  322,95'
 '  43,9' '  26,9' '  26,1' '  29,1' '  29,5' '  42.4' '  35.9' '  30.1'
 '  35.2' '  34.7' '  47.2' '  43.2' '  27.5' '  31.3' '  43.0' '  29.3'
 '  36.8' '  33.1' '  46.8' '  36.2' '  15.2' '  18.2' '  20.7' '  30.9'
 '  45.9' '  24.8' '  38.1' '  48.8' '  20.6' '   5.0' '   8.7' '  16.3'
 '  20.8' '  26.9' '  38.2' '  33.6' '  45.6' '  54.8' '  55.1' '  31.8'
 '  40.3' '  52.1' '  47.3' '  32.9' '  35.8' '  40.5' '  46.9' '  51.2'
 '  42.5' '  42.0' '  44.5' '  35.1' '  36.4' '  53.8' '  60.0' '  49.9'
 '  50.5' '  42.6' '  34.5' '  38.4' '  34.2' '  39.3' '  46.1' '  33.2'
 '  50.1' '  43.6' '  40.2' '  51.8' '  31.0' '  53.3' '  45.0' '  50.3'
 '  63.5' '  58.2' '  44.2' '  38.5' '  61.9' '  41.9' '  44.7' '  50.9'
 '  34.8' '  43.1' '  51.9' '  41.2' '  42.9' '  58.5' '  66.5' '  61.7'
 '  54.7' '  43.9' '  50.7' '  59.7' '  63.0' '  64.9' '  65.7' '  62.7'
 '  67.5' '  62.3' '  53.0' '  55.2' '  58.6' '  64.4' '  67.0' '  49.5'
 '  46.2' '  56.7' '  63.6' '  68.2' '  71.0' '  74.1' '  74.3' '  62.5'
 '  62.2' '  65.5' '  69.5' '  76.3' '  64.2' '  72.1' '  78.7' '  77.5'
 '  76.5' '  78.1' '  75.1' '  79.4' '  71.7' '  76.1' '  82.1' '  73.6'
 '  66.7' '  61.6' '  71.9' '  71.2' '  63.3' '  75.0' '  83.2' '  85.0'
 '  85.3' '  69.9' '  65.4' '  79.8' '  76.2' '  72.6' '  80.7' '  81.8'
 '  80.0' '  81.7' '  76.6' '  73.4' '  79.7' '  67.7' '  82.3' '  81.2'
 '  70.7' '  71.6' '  68.5' '  66.1' '  68.0' '  73.8' '  75.9' '  70.3'
 '  69.1' '  74.8' '  75.5' '  75.6' '  71.3' '  70.4' '  71.4' '  72.4'
 '  68.8' '  62.4' '  60.4' '  63.4' '  63.9' '  76.8' '  77.2' '  67.1'
 '  67.2' '  75.3' '  75.7' '  67.8' '  69.2' '  63.8' '  60.6' '  65.2'
 '  76.0' '  74.0' '  77.4' '  77.0' '  74.7' '  61.2' '  70.2' '  55.8'
 '  53.4' '  61.8' '  53.9' '  52.7' '  50.4' '  63.1' '  71.1' '  56.9'
 '  55.4' '  43.5' '  39.6' '  36.5' '  34.0' '  37.5' '  50.8' '  28.4'
 '  28.0' '  39.9' '  47.0' '  52.0' '  51.6' '  57.5' '  54.6' '  53.7'
 '  52.2' '  54.4' '  57.9' '  53.6' '  60.5' '  44.1' '  40.7' '  45.5'
 '  48.0' '  39.2' '  45.3' '  39.0' '  34.9' '  31.4' '  21.9' '  27.7'
 '  42.3' '  41.5' '  31.6' '  28.3' '  33.8' '  36.3' '  39.4' '  30.2'
 '  40.9' '  49.0' '  31.7' '  27.6' '  27.1' '  26.8' '  30.0' '  23.1'
 '  26.4' '  29.4' '  30.5' '  44.3' '  40.4' '  40.0' '  40.8' '  34.6'
 '  28.2' '  27.4' '  23.7' '  16.4' '  17.5' '  23.4']
Unique values per 'STP_ATTRIBUTES':
 ['24' 'twenty-four']
Unique values per 'MAX_ATTRIBUTES':
 [' ' '*']
Unique values per 'MIN_ATTRIBUTES':
 [' ' '*']
Unique values per 'PRCP_ATTRIBUTES':
 ['G' 'I']

### This was helpful, since there are a lot of things that dont make sense: 

- 1) STATION is a number. The datatype should be int not object. (Third error)
- 2) TEMP is also number. There is no reason why this would be an object. (fourth error)
- 3) STP_ATTRIBUTES has the value 24 and twenty-four. I would also go for the number here. Having both doesnt make sense. (fifth error)
- 4) MAX and MIN_ATTRIBUTES seem to have a purpose of indicating some rows. Thats badly structured. But right now we dont really know if its important so we leave it. 
- 5) Also we see that TEMP contains some values with "." and some with ",". That should be changed aswell (error six)

In [16]:
# Issue 1: Convert STATION to Int64 by replacing non-numeric values with NaN, then casting to Int64
df['STATION'] = pd.to_numeric(df['STATION'], errors='coerce').astype('Int64')

# Issue 2: Convert TEMP to float by replacing non-numeric values with NaN, then casting to float
df['TEMP'] = pd.to_numeric(df['TEMP'], errors='coerce')

# Issue 3: Standardize STP_ATTRIBUTES by replacing 'twenty-four' with 24, then converting to Int64
df['STP_ATTRIBUTES'] = df['STP_ATTRIBUTES'].replace('twenty-four', 24)
df['STP_ATTRIBUTES'] = pd.to_numeric(df['STP_ATTRIBUTES'], errors='coerce').astype('Int64')

#Issue 4: Replace commas with dots in the TEMP column and convert to float
df['TEMP'] = df['TEMP'].astype(str).str.replace(',', '.').astype(float)

# Check the results
print(df.dtypes)
df.head()

STATION                      Int64
DATE                datetime64[ns]
LATITUDE                   float64
LONGITUDE                  float64
ELEVATION                  float64
NAME                        object
TEMP                       float64
TEMP_ATTRIBUTES              int64
DEWP                       float64
DEWP_ATTRIBUTES              int64
SLP                        float64
SLP_ATTRIBUTES               int64
STP                        float64
STP_ATTRIBUTES               Int64
VISIB                      float64
VISIB_ATTRIBUTES             int64
WDSP                       float64
WDSP_ATTRIBUTES              int64
MXSPD                      float64
GUST                       float64
MAX                        float64
MAX_ATTRIBUTES              object
MIN                        float64
MIN_ATTRIBUTES              object
PRCP                       float64
PRCP_ATTRIBUTES             object
SNDP                       float64
FRSHTT                       int64
dtype: object

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,TEMP,TEMP_ATTRIBUTES,DEWP,DEWP_ATTRIBUTES,...,MXSPD,GUST,MAX,MAX_ATTRIBUTES,MIN,MIN_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SNDP,FRSHTT
0,72565003017,2018-01-01,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",284.75,24,5.5,24,...,9.9,999.9,28.0,,3.0,,0.0,G,999.9,1000
1,72565003017,2018-01-02,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",294.35,24,7.3,24,...,9.9,999.9,43.0,,3.0,,0.0,G,999.9,0
2,72565003017,2018-01-03,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",294.35,24,3.0,24,...,15.9,24.1,53.1,,10.9,,0.0,G,999.9,0
3,72565003017,2018-01-04,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",307.75,24,11.6,24,...,8.9,999.9,53.1,,17.1,,0.0,G,999.9,0
4,72565003017,2018-01-05,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",309.45,24,11.4,24,...,14.0,999.9,55.9,,23.0,,0.0,G,999.9,0

### Lets also check the other columns for unique values.

In [20]:
# Iterate over each column and display unique values
for column in df.columns:
    unique_values = df[column].unique()
    print(f"Column '{column}' has {len(unique_values)} unique values:")
    print(unique_values)

Column 'STATION' has 2 unique values:
<IntegerArray>
[72565003017, <NA>]
Length: 2, dtype: Int64
Column 'DATE' has 365 unique values:
<DatetimeArray>
['2018-01-01 00:00:00', '2018-01-02 00:00:00', '2018-01-03 00:00:00',
 '2018-01-04 00:00:00', '2018-01-05 00:00:00', '2018-01-06 00:00:00',
 '2018-01-07 00:00:00', '2018-01-08 00:00:00', '2018-01-09 00:00:00',
 '2018-01-10 00:00:00',
 ...
 '2018-12-22 00:00:00', '2018-12-23 00:00:00', '2018-12-24 00:00:00',
 '2018-12-25 00:00:00', '2018-12-26 00:00:00', '2018-12-27 00:00:00',
 '2018-12-28 00:00:00', '2018-12-29 00:00:00', '2018-12-30 00:00:00',
 '2018-12-31 00:00:00']
Length: 365, dtype: datetime64[ns]
Column 'LATITUDE' has 2 unique values:
[39.8328   49.009724]
Column 'LONGITUDE' has 2 unique values:
[-104.6575      2.547778]
Column 'ELEVATION' has 2 unique values:
[  1650.2 165020. ]
Column 'NAME' has 2 unique values:
['DENVER INTERNATIONAL AIRPORT, CO US'
 'PARIS CHARLES DE GAULLE AIRPORT, FRANCE']
Column 'TEMP' has 271 unique values:
[284.75 294.35 307.75 309.45 313.35 312.95 306.35 321.35 322.45 304.15
 308.45 304.35 309.05    nan  42.4   35.9   30.1   35.2   34.7   47.2
  43.2   27.5   31.3   43.    29.3   36.8   33.1   46.8   36.2   15.2
  18.2   20.7   30.9   45.9   24.8   38.1   48.8   20.6    5.     8.7
  16.3   20.8   26.9   38.2   33.6   45.6   54.8   55.1   31.8   40.3
  52.1   47.3   32.9   35.8   40.5   46.9   51.2   42.5   42.    44.5
  35.1   36.4   53.8   60.    49.9   50.5   42.6   34.5   38.4   34.2
  39.3   46.1   33.2   50.1   43.6   40.2   51.8   31.    53.3   45.
  50.3   63.5   58.2   44.2   38.5   61.9   41.9   44.7   50.9   34.8
  43.1   51.9   41.2   42.9   58.5   66.5   61.7   54.7   43.9   50.7
  59.7   63.    64.9   65.7   62.7   67.5   62.3   53.    55.2   58.6
  64.4   67.    49.5   46.2   56.7   63.6   68.2   71.    74.1   74.3
  62.5   62.2   65.5   69.5   76.3   64.2   72.1   78.7   77.5   76.5
  78.1   75.1   79.4   71.7   76.1   82.1   73.6   66.7   61.6   71.9
  71.2   63.3   75.    83.2   85.    85.3   69.9   65.4   79.8   76.2
  72.6   80.7   81.8   80.    81.7   76.6   73.4   79.7   67.7   82.3
  81.2   70.7   71.6   68.5   66.1   68.    73.8   75.9   70.3   69.1
  74.8   75.5   75.6   71.3   70.4   71.4   72.4   68.8   62.4   60.4
  63.4   63.9   76.8   77.2   67.1   67.2   75.3   75.7   67.8   69.2
  63.8   60.6   65.2   76.    74.    77.4   77.    74.7   61.2   70.2
  55.8   53.4   61.8   53.9   52.7   50.4   63.1   71.1   56.9   55.4
  43.5   39.6   36.5   34.    37.5   50.8   28.4   28.    39.9   47.
  52.    51.6   57.5   54.6   53.7   52.2   54.4   57.9   53.6   60.5
  44.1   40.7   45.5   48.    39.2   45.3   39.    34.9   31.4   21.9
  27.7   42.3   41.5   31.6   28.3   33.8   36.3   39.4   30.2   40.9
  49.    31.7   27.6   27.1   26.8   30.    23.1   26.4   29.4   30.5
  44.3   40.4   40.    40.8   34.6   28.2   27.4   23.7   16.4   17.5
  23.4 ]
Column 'TEMP_ATTRIBUTES' has 2 unique values:
[24 42]
Column 'DEWP' has 271 unique values:
[ 5.5  7.3  3.  11.6 11.4 18.1 25.2 23.  24.9 24.4 18.9 18.2 22.7 20.7
 16.  -4.1  7.5 10.5 14.5 18.7 23.4 11.1  9.3 12.6 15.2 12.5  4.3 14.1
 20.9 14.3 18.5 20.5 22.2 23.9 23.1 19.8 19.6 20.1 11.8  9.5 15.4 19.4
 22.4 13.2 11.9 12.4 -0.4  3.1  9.7 16.8 13.9  2.6 10.6 13.4 16.1 15.1
  5.4  3.2  1.6  6.8  5.9 13.8 17.8  7.8 18.3 20.6 28.4 15.8 21.2 26.2
 19.5 18.8 24.7 31.4 27.5 26.7 28.8 28.2 28.5 26.9 22.5 24.  12.2  8.2
 25.9 30.9 29.8 26.  24.2 14.  14.6 23.7 32.6 33.  36.3 26.1 25.4 29.
 31.5 40.2 40.5 41.2 36.8 32.8 38.1 37.2 35.8 38.9 39.  46.2 50.4 49.1
 48.3 43.4 39.3 42.6 44.5 45.1 40.3 42.7 45.2 42.  37.4 37.5 33.2 48.8
 42.4 40.8 30.7 30.  35.9 37.8 32.7 36.7 34.9 30.1 28.  37.6 47.6 36.1
 39.2 49.  55.3 55.6 54.7 50.3 47.1 45.7 43.  46.6 40.4 33.4 43.8 48.2
 43.6 39.1 44.7 50.7 50.  50.1 46.8 42.8 41.5 53.6 54.2 58.5 58.2 51.
 47.3 45.6 50.8 57.6 61.5 58.8 57.1 55.9 56.4 55.5 42.3 45.8 48.1 44.
 47.  54.8 53.2 47.8 46.7 43.5 51.4 49.7 50.9 46.5 53.4 38.  39.9 43.9
 41.  44.3 42.2 42.1 44.8 51.7 52.6 35.3 34.2 33.1 24.5 21.7 41.8 37.7
 51.1 34.6 25.  21.5 30.3 38.7 43.1 38.3 36.5 35.  32.1 32.4 22.9 14.4
 18.4 29.5 32.  30.5 26.6 35.5 41.6 32.2 26.8 27.  21.8 28.6 31.9 26.5
 27.7 27.2 17.6 26.4  7.2 13.  21.9 20.4 15.9 17.2 14.9 10.8 18.  21.3
 11.2 19.3 27.4 28.1 25.7 15.3 -0.2  2.2  5.1  6.5 12.1 12.3 17.7 14.7
  8.7 10.2 13.1  4.7  7.9]
Column 'DEWP_ATTRIBUTES' has 1 unique values:
[24]
Column 'SLP' has 203 unique values:
[1030.9 1029.4 1026.7 1022.  1020.9 1017.9 1013.  1017.6 1009.2  997.
 1014.  1017.1 1025.9 1025.2 1027.4 1038.3 1027.8 1020.  1007.2 1004.2
 1009.9 1017.5 1022.4 1024.4 1013.5 1008.6 1023.9 1025.4 1030.2 1016.2
 1007.5 1020.2 1021.5 1010.9 1012.6 1011.9 1015.6 1019.2 1012.5 1017.7
 1020.4 1021.7 1013.4 1000.6 1002.3 1028.2 1021.8 1019.5 1010.6 1009.4
 1008.8 1011.1 1006.2  999.5 1010.8 1023.6 1007.  1008.3 1024.2 1022.8
 1014.9 1000.1 1001.4 1002.6 1012.8 1014.5 1004.5 1009.1 1003.2 1018.4
 1018.6 1013.9 1016.5 1006.8 1015.5 1011.4 1011.3 1015.4 1001.6 1015.3
 1019.9  996.9 1018.3 1018.9 1010.7  997.5 1021.  1009.3 1020.1 1020.7
 1015.1 1026.4 1017.2 1018.7  998.3 1009.6 1019.6 1018.  1012.1 1012.3
 1006.4 1002.5 1008.  1011.6 1005.7 1005.  1013.2 1020.5 1008.1 1011.
 1005.6 1002.1 1008.9 1008.2 1007.1 1005.3 1001.5 1015.  1010.5 1005.5
 1000.4 1004.  1010.  1003.3 1001.9 1004.9 1011.5 1014.6 1009.  1006.5
 1008.4 1014.4 1003.8  999.9 1013.8 1005.9 1011.8 1023.8 1016.1 1015.7
 1013.7 1009.7 1015.9 1017.3 1012.  1019.4 1018.5 1019.3 1016.6 1016.4
 1016.3 1020.3 1019.  1014.8 1016.8 1010.2 1011.2 1013.1 1018.8 1006.6
 1002.7 1009.5 1010.4 1007.6 1023.  1006.1 1004.8 1008.5 1010.1 1005.8
 1012.9 1014.2 1004.3 1006.9 1029.8 1029.1 1021.4 1019.7 1025.6 1012.4
 1014.1 1004.4 1012.2 1021.6 1014.7 1033.7 1027.3 1018.2 1020.8 1013.3
 1004.7 1001.  1023.1 1002.  1023.5 1024.3 1027.7 1007.4 1018.1 1022.7
 1010.3 1015.2 1006.7]
Column 'SLP_ATTRIBUTES' has 14 unique values:
[24 23 22 16 11 17 18 21 19 20 15 13 14 10]
Column 'STP' has 164 unique values:
[839.1 839.  839.3 836.5 835.9 834.3 830.5 832.9 828.  819.3 829.3 832.4
 839.5 839.2 840.8 844.5 838.9 835.5 827.3 824.5 826.3 830.8 835.7 837.
 826.5 837.2 843.3 834.  834.6 836.  828.8 831.3 827.5 830.6 836.2 829.7
 830.  833.4 831.1 826.9 829.6 821.1 820.3 826.4 832.1 831.8 826.1 827.2
 829.1 827.  832.3 822.1 835.4 836.9 827.4 828.3 838.6 838.4 838.5 832.8
 821.8 821.  823.1 829.2 833.3 827.1 830.1 824.4 834.4 832.2 832.7 832.
 830.9 831.4 822.7 833.7 837.3 829.4 834.1 821.2 837.6 834.9 836.4 840.5
 841.3 826.2 822.8 825.4 838.7 834.5 833.8 835.6 833.5 838.3 830.3 827.6
 831.6 829.9 831.  831.9 833.9 828.1 826.  833.6 836.1 833.  830.4 831.5
 835.3 844.8 845.4 839.8 839.7 838.1 834.7 835.  837.7 836.6 834.8 836.7
 841.8 840.9 838.8 838.  841.1 840.3 837.4 837.8 828.5 833.1 834.2 840.
 842.5 833.2 829.8 842.2 844.7 843.1 838.2 836.3 837.5 830.7 824.2 843.
 843.9 841.9 832.5 835.8 835.2 824.9 820.7 825.1 824.3 821.3 819.6 825.2
 840.4 837.9 825.8 828.7 828.2 825.5 824.7 824.8]
Column 'STP_ATTRIBUTES' has 1 unique values:
<IntegerArray>
[24]
Length: 1, dtype: Int64
Column 'VISIB' has 49 unique values:
[ 7.1  7.7 10.   9.8  9.9  9.7  7.2  3.5  9.1  8.4  5.8  7.3  6.7  5.1
  0.7  6.5  8.   8.5  3.4  6.6  8.9  6.1  3.1  9.5  7.4  8.3  6.8  9.6
  8.6  9.2  4.6  5.7  9.3  8.1  7.9  5.9  6.3  7.5  7.6  5.5  6.4  8.7
  6.2  2.6  5.2  9.4  4.2  6.   6.9]
Column 'VISIB_ATTRIBUTES' has 1 unique values:
[24]
Column 'WDSP' has 96 unique values:
[ 5.   5.6  9.7  6.5  6.7  5.1  6.1  6.6  9.8  8.4  9.5  5.8  7.   9.
  6.3  4.7  9.1  9.4 11.6 11.4 11.3 14.  10.7  7.7 10.6  9.2  7.8  5.9
 10.1 10.4  7.6 11.8 10.   9.6  7.1  6.9  8.7 11.7  7.5  5.5  6.2 12.7
 11.2  8.2 11.9 16.2 20.5  8.1  8.8  8.   8.5 13.1  7.3  7.2  9.3  9.9
 13.4  7.9 12.3 20.8 23.2  7.4 20.  10.9 13.7 17.2 12.4  4.3 13.6 13.5
 13.   6.8 10.2  8.9 10.3 11.   8.3 12.8 10.5 13.3  6.4 10.8  4.6 11.1
  6.  13.9  5.2 11.5 12.6  8.6  4.9  5.3 15.1 12.5  4.1  4.4]
Column 'WDSP_ATTRIBUTES' has 1 unique values:
[24]
Column 'MXSPD' has 30 unique values:
[ 9.9 15.9  8.9 14.  11.1 13.  15.  17.1 22.9 18.1 25.1 24.1 27.  12.
 26.  22.  21.  19.  20.  28.  32.1 29.9 28.9 39.  38.1 33.  31.1 40.
  7.   8. ]
Column 'GUST' has 40 unique values:
[999.9  24.1  27.   32.1  22.9  33.   41.   36.9  28.9  39.   22.   18.1
  26.   28.   20.   38.1  31.1  17.1  52.1  35.9  21.   34.   35.   40.
  48.   49.   42.   19.   58.1  47.   29.9  15.   45.1  25.1  42.9  49.9
  15.9  46.   14.   54. ]
Column 'MAX' has 75 unique values:
[  28.    43.    53.1   55.9   62.1   48.9   68.    57.    46.    48.
   34.    50.    64.9   66.9   44.1   46.9   54.    45.    52.    57.9
   63.    36.    60.1   61.    19.    66.    55.    69.1 9999.9   23.
   21.9   25.    35.1   41.    59.    70.    71.1   51.1   64.    73.
   72.    73.9   78.1   79.    39.    80.1   82.9   75.    90.    77.
   81.    86.    91.    93.9   87.1   84.    91.9   93.    95.    96.1
   97.    82.    89.1  100.9  105.1   99.    98.1   84.9   88.    75.9
   42.1   37.    37.9   32.    30. ]
Column 'MAX_ATTRIBUTES' has 2 unique values:
[' ' '*']
Column 'MIN' has 72 unique values:
[ 3.  10.9 17.1 23.  25.  26.1 24.1 34.  21.  19.  15.1 -4.  26.2 32.
  9.  14.  16.  21.9 18.  10.  36.   0.  35.1  7.  28.  -2.9 -7.1  8.1
 45.  12.9 30.9 30.  51.1 39.  33.1 48.9 43.  28.9 50.  27.  42.1 46.
 39.9 41.  46.9 44.1 48.2 52.  54.  55.  48.  57.  60.1 57.9 61.  55.9
 63.  59.  57.2 62.1 64.  66.  68.  55.4 53.1 51.8 37.  30.2 19.4 37.9
 19.9  5. ]
Column 'MIN_ATTRIBUTES' has 2 unique values:
[' ' '*']
Column 'PRCP' has 32 unique values:
[0.   0.01 0.17 0.03 0.07 0.23 0.14 0.02 0.11 0.04 0.33 0.32 0.05 0.31
 0.06 0.1  0.15 0.64 0.3  0.66 0.09 0.27 0.13 0.21 0.43 0.38 0.24 0.16
 0.36 0.08 0.22 0.19]
Column 'PRCP_ATTRIBUTES' has 2 unique values:
['G' 'I']
Column 'SNDP' has 5 unique values:
[999.9   1.2   3.9   3.1   2. ]
Column 'FRSHTT' has 13 unique values:
[  1000      0  11000  10000 111000 101000 100000  11010 110000  10010
 111110  10110     10]

### 'Gust' and 'Max' has values that look like placeholders (999.9 and 9999.9) 
Lets replace these values with the mean of the non-outliers value.

In [30]:
# Calculate the mean for 'GUST' and 'MAX' columns, excluding the outliers
gust_mean = df.loc[df["GUST"] != 999.9, "GUST"].mean()
max_mean = df.loc[df["MAX"] != 9999.9, "MAX"].mean()

# Replace outlier values with the mean in 'GUST' and 'MAX'
df.loc[df["GUST"] == 999.9, "GUST"] = gust_mean
df.loc[df["MAX"] == 9999.9, "MAX"] = max_mean

# Display the DataFrame to confirm the changes
df

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,TEMP,TEMP_ATTRIBUTES,DEWP,DEWP_ATTRIBUTES,...,MXSPD,GUST,MAX,MAX_ATTRIBUTES,MIN,MIN_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SNDP,FRSHTT
2,72565003017,2018-01-03,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",294.35,24,3.0,24,...,15.9,24.1,53.1,,10.9,,0.00,G,999.9,0
9,72565003017,2018-01-10,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",322.45,24,24.4,24,...,17.1,27.0,68.0,,34.0,,0.00,G,999.9,10000
10,72565003017,2018-01-11,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",304.15,24,18.9,24,...,22.9,32.1,57.0,,21.0,,0.17,G,999.9,11000
11,72565003017,2018-01-12,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",308.45,24,18.2,24,...,18.1,22.9,46.0,,21.0,,0.00,G,999.9,11000
20,72565003017,2018-01-21,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",NaN,24,23.4,24,...,24.1,32.1,48.0,,23.0,,0.07,G,999.9,111000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,72565003017,2018-12-19,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",42.50,24,17.7,24,...,24.1,33.0,57.0,,25.0,,0.00,G,999.9,0
354,72565003017,2018-12-21,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",40.80,24,8.7,24,...,26.0,35.0,63.0,,19.0,,0.00,G,999.9,0
355,72565003017,2018-12-22,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",34.60,24,18.5,24,...,15.9,25.1,63.0,,24.1,,0.00,G,999.9,1000
360,72565003017,2018-12-27,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",23.70,24,13.1,24,...,18.1,28.0,37.0,,12.9,,0.00,G,999.9,1000
364,72565003017,2018-12-31,39.8328,-104.6575,1650.2,"DENVER INTERNATIONAL AIRPORT, CO US",23.40,24,11.1,24,...,21.0,29.9,53.1,,7.0,,0.00,G,999.9,1000

No further errors could be found. Here is a list of all found errors: 

- date is not an datetime object
- duplicated rows
- object instead of number
- object instead of float 
- mixed data types in one column (24 and twenty-four)
- mixed "." and "." for float numbers 
- placeholder values (999.9 and 9999.9 in GUST and MAX